### PR TITLE
Use StringDecoder for Buffers in WritableStream

### PR DESCRIPTION
**Pull request by ajafff**
http://stackoverflow.com/questions/12121775/convert-streamed-buffers-to-utf8-string

### CODE REVIEW

**Comment by fb55** [comment]
Could you add a test case that fails without this?

**Comment by spruehstuhl** [comment]
```javascript
"use strict";

var ParserStream = require('htmlparser2').WritableStream;
var Buffer = require('buffer').Buffer;
var assert = require('assert');

var parser = new ParserStream({
    ontext:function(text){
        assert.equal(text, '€');
    }
});

parser.write(new Buffer([0xE2, 0x82]));
parser.write(new Buffer([0xAC]));
```
Without the fix this should fail `AssertionError: "��" == "€"`
After applying the fix those 2 Buffers will be concatenated and result in '€'

**Comment by fb55** [comment]
Hm, AFAICT, this should be fixed when concatinating text events as discussed with @jails in #124.

**Comment by spruehstuhl** [comment]
I get your point, but this problem is not inherent to text nodes. It could affect everything which contains characters that are not specified in ASCII (attributes, CDATA, comments, ...)
Also I looked at the implementation of high5. The concatenating of text events you mentioned is done by concatenating multiple string chunks to one string "buffer" (`this._buffer`)
Unfortunately it will not solve this problem, because 
```javascript
new Buffer([0xE2, 0x82]).toString() + new Buffer([0xAC]).toString() !== '€' //results in '���' instead
```

When working with Buffers in a streaming fashion you have to use StringDecoder to get utf8 right

**Comment by philiiiiiipp** [comment]
I think @ajafff is very right. I ran into trouble when parsing web pages, especially since the behaviour is quite unpredictable because a cut right between the two bytes happens quite rarely.

I think it would be beneficial to add this information to the [/wiki/Parser-options](https://github.com/fb55/htmlparser2/wiki/Parser-options). Would have saved me some troubles at least.

**Comment by fb55** [comment]
I forgot about this, sorry. This needs a test case in the `test` dir (as a new file – have a look at `api.js`) and quotes have to be double quotes (that's why the tests fail). Looks good otherwise.

**Comment by ajafff** [comment]
@fb55 changed single quotes to double quotes, added test
PTAL

**Comment by fb55** [comment]
Awesome, thanks!

**Pull request merged**
