### PR TITLE
Fixing circular dependency

### LINKED ISSUE #223: Circular dependency
Hi,

I have htmlparser2 as a dependency my project, and it's causing me some troubles because of a circular dependency. It causes my lib to not be able to be packaged with rollup.js.

The ciruclar dependency is in `htmlparser2/lib/index.js` that requires `htmlparser2/lib/FeedHandlerjs` and vice versa.

The rollup issue is here https://github.com/rollup/rollup/issues/1674#issuecomment-336254281

It would be great to fix this, it would allow every project using cheerio and/or htmlparser2 to be packaged with rollup :)

Thanks a lot!

### PR DESCRIPTION
**Pull request by GreenGremlin**
Fixes #223

### CODE REVIEW

**Comment by GreenGremlin** [comment]
Still hoping for word on when this might be released.

**Comment by fb55** [comment]
Released a new version!

**Comment by GreenGremlin** [comment]
Thanks!

**Comment by dhruvarora93** [comment]
So I am using react-html-parser and I am getting this error. Any ideas why ?

**Pull request merged**
