### PR TITLE
Set attribute value to true for boolean attributes

### PR DESCRIPTION
**Pull request by pravdomil**
see diff

### CODE REVIEW

**Comment by pravdomil** [comment]
should I fix the tests?

**Comment by fb55** [comment]
Breaking change, sadly can't be adopted :/

**Comment by pravdomil** [comment]
@fb55 semver?

**Comment by fb55** [comment]
I don't see enough of a reason to change the API this way. Consumers expect a certain structure right now, this would break existing code and would be difficult to update.

**Comment by pravdomil** [comment]
Do you see any other way how to distinguish between `<tag prop="">` and `<tag prop>`?

**Comment by fb55** [comment]
As disappointing as this may sound, but the two are semantically equivalent, so there shouldn't be a need to distinguish them.

**Comment by pravdomil** [comment]
yes, that's valid for `html` not for `jsx`, but you develop `html` parser

**Pull request closed without merging**
