### PR TITLE
Fix npm files filter

### PR DESCRIPTION
**Pull request by TrySound**
For smaller package

### CODE REVIEW

**Comment by TrySound** [comment]
\cc @fb55

**Comment by TrySound** [comment]
\cc @fb55 And this

**Comment by TrySound** [comment]
Thank you! Don't forget to release and publish.

**Comment by fb55** [comment]
Will have to wait. A new release should at least include some noticeable changes.

**Comment by TrySound** [comment]
@fb55 Okay..

**Pull request merged**
