### PR TITLE
Add startIndex and endIndex positional attributes to the parser

### PR DESCRIPTION
**Pull request by dax**
Add start and end positional attributes to the parser (see #53).

I can't figure out how to easily add some tests to the existing ones.

### CODE REVIEW

**Comment by bacloud22** [comment]
This is very interesting, thank you guys for making this possible.
Could you please make it up to the main API ? I can't see a reference on how to get `startIndex` and `endIndex` on README in any callback.

**Comment by fb55** [comment]
@bacloud22 See my response in https://github.com/fb55/htmlparser2/issues/1224#issuecomment-1166629597

**Comment by altano** [comment]
@fb55 do you [live in Nebraska](https://xkcd.com/2347/) by any chance?

**Comment by bacloud22** [comment]
If someone lives in Nebraska, or not, what matters more is responding to random person in descent manners. Not nerdish manners. Motivated by people and ideas. Not only ideas. @alan

**Comment by fb55** [comment]
@altano Thanks, this made my day ❤️

**Pull request merged**
