### PR TITLE
This can be very useful to be able to extend the tokenizer trough inheritance.

### PR DESCRIPTION
**Pull request by LeonFedotov**

### CODE REVIEW

**Comment by fb55** [comment]
Nice idea. Could you add a simple test case?

**Comment by LeonFedotov** [comment]
sounds good, working on it.

**Comment by LeonFedotov** [comment]
Done, also I thought may be we can add node 4/5 to travis?

**Comment by fb55** [comment]
Thanks a lot!

The Travis upgrade was done in #158.

**Comment by LeonFedotov** [comment]
Awesome :)

**Pull request merged**
