### PR TITLE
GH-41 Replace third party content in tests with our own

### PR DESCRIPTION
**Pull request by jfahrenkrug**
I went ahead and replaced all the craigslist content in the test RDF files with fake content. This addresses https://github.com/fb55/htmlparser2/issues/41

### CODE REVIEW

**Comment by fb55** [comment]
Thanks for the patch! I don't think this completely eliminates the copyright claims, bringing some originality into the game is nice, though. If anyone knows/finds any open source/public domain/CC licensed feeds, that would be an even better replacement.

**Comment by jfahrenkrug** [comment]
@fb55 Yes, I agree. It's actually surprisingly difficult to find public domain __feed__ content :)

**Comment by AndreasMadsen** [comment]
The wikipedia RSS should be fine. https://en.wikipedia.org/w/index.php?title=Special:RecentChanges&feed=atom

see also: https://en.wikipedia.org/wiki/Wikipedia:Syndication

**Comment by fb55** [comment]
@AndreasMadsen Great suggestion :)

**Pull request merged**
