### PR TITLE
Add support for condtional comment

### PR DESCRIPTION
**Pull request by zimski**
Now the parser support conditional comment
- The parser will fire openCondtionalComment when he pase some thing like
  .
- The html between the two tags is parsed as usual way

### CODE REVIEW

**Comment by fb55** [comment]
I really don't know if I want this feature. On the one hand, it's outdated technology and won't be used on modern pages, on the other hand, I had a case where I wanted this recently and just went with a hack. 

Anyway, just to get started, this should definitely be enabled by an option (HTML5 should remain the default). A link to some documentation from Microsoft to ensure all cases are covered would be nice as well.

**Comment by zimski** [comment]
Hi , thx for the quick reply.

I really don't know if I want this feature. On the one hand, it's outdated
> technology and won't be used on modern pages, on the other hand, I had a
> case where I wanted this recently and just went with a hack.
>
I agree with you .. the html conditional comment is a crap and are no
longer supported in IE10 (good news :) )
However, this kind of comment will still on a lot of html pages over the
web for some years, so in my mind it's a good thing that be natively
supported.

Anyway, just to get started, this should definitely be enabled by an option
> (HTML5 should remain the default).
>
yes, i will do it

> A link to some documentation from Microsoft to ensure all cases are
> covered would be nice as well.
>
MSDN https://msdn.microsoft.com/en-us/library/ms537512(v=vs.85).aspx

I added also this case (it's not documented in MSDN ... love Microsoft :) )

 
        <link rel="stylesheet" media="screen, projection"
type="text/css"
href="http://www.website.com/_ui/desktop/assets/css/common.css" />
        .....
    *

—
> Reply to this email directly or view it on GitHub
> <https://github.com/fb55/htmlparser2/pull/146#issuecomment-128531982>.
>



-- 
*CHADDA Chakib*
*Tel.* 06 80 95 76 31
*17 bd Maurice Berteaux.*
*94100 St Maur des fossés*

**Comment by fb55** [comment]
Not a feature that is part of today's web anymore, closing this.

**Comment by cossssmin** [comment]
MSO comments, like the one in @zimski's reply above, are still used (and necessary) in HTML emails. Would have been a very useful feature for email developers.

**Pull request closed without merging**
